import { NearMark } from '@/components/marks';

/**
 * The footer carries the fee disclosure.
 *
 * It belongs here rather than stacked under the quote at the bottom edge of the
 * stage frame: a paid-placement disclosure has to be findable, and at the foot
 * of the tour it was competing with the CTA for the same moment.
 */
export function Footer() {
  return (
    <footer>
      <div className="shell">
        <div className="fgrid">
          <div className="fcol">
            <a className="brand" href="#top" style={{ marginBottom: 18, color: '#fff' }}>
              <NearMark />
            </a>
            <p className="caption" style={{ maxWidth: '34ch', color: 'rgba(255,255,255,.55)' }}>
              Live your financial life onchain, privately. One account,
              30+ chains.
            </p>
            <div className="socials"><a href="https://x.com/nearprotocol" aria-label="X" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z" /></svg></a><a href="https://discord.gg/nearprotocol" aria-label="Discord" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.317 4.3698a19.7913 19.7913 0 0 0-4.8851-1.5152.0741.0741 0 0 0-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 0 0-.0785-.037 19.7363 19.7363 0 0 0-4.8852 1.515.0699.0699 0 0 0-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 0 0 .0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 0 0 .0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 0 0-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 0 1-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 0 1 .0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 0 1 .0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 0 1-.0066.1276 12.2986 12.2986 0 0 1-1.873.8914.0766.0766 0 0 0-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 0 0 .0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 0 0 .0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 0 0-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z" /></svg></a></div>
          </div>
          <div className="fcol">
            <h4>Product</h4>
            <a href="https://near.com/home">Dashboard</a>
            <a href="https://near.com/support">Support</a>
          </div>
        </div>

        <p className="rdisc">
          The Rollup is paid a share of the fees generated by traders who sign up
          through this page. That creates an incentive, and you should weigh it
          accordingly.
        </p>

        {/* THE REBATE, IN FULL. Supplied verbatim by counsel — do not reword,
            reflow or summarise it. It sits under the paid-placement notice
            because the two describe the same arrangement from either side: what
            The Rollup is paid, and what the reader gets back.

            IT IS THE FOOT OF THE PAGE ON PURPOSE. `<Footer />` is rendered by
            `LightZone` on every viewport, unlike the tour above it, which is two
            compositions that swap at 1080px — a disclosure placed there would
            have to exist twice and could drift. */}
        <p className="rdisc">
          Users who sign up through this page receive 20% of near.com platform
          fees back in NEAR. Third-party fees, network/gas fees and other fees
          are excluded. Rebates equal 20% of the NEAR received on conversion of
          those platform fees and are normally credited immediately afterwards,
          subject to processing and network delays. The rebate, including its
          rate and availability, may be changed or discontinued prospectively on
          notice in accordance with the near.com Terms of Service. Changes will
          not affect rebates already earned.
        </p>

        <div className="fbot">
          <span>© 2026 near.com. Built on NEAR.</span>
          <span style={{ display: 'flex', gap: 20 }}>
            <a href="https://near.com/terms">Terms</a>
            <a href="https://near.com/privacy">Privacy</a>
          </span>
        </div>
      </div>
    </footer>
  );
}
